image: debian:bookworm-slim

before_script:
  - apt-get update -qq
  - apt-get install -y --no-install-recommends gcc-arm-none-eabi libnewlib-arm-none-eabi make qemu-system-arm python3 psmisc
stages:
  - build_and_test

run_regression_tests:
  stage: build_and_test
  script:
    - echo "========================================================="
    - echo "Starting Regression Tests for PTL Scheduler"
    - echo "========================================================="
    - python3 generate_tests.py
    - python3 run_tests.py